const indianStates = [
  { id: "AN", description: "Andaman and Nicobar Islands" },
  { id: "AP", description: "Andhra Pradesh" },
  { id: "AR", description: "Arunachal Pradesh" },
  { id: "AS", description: "Assam" },
  { id: "BR", description: "Bihar" },
  { id: "CH", description: "Chandigarh" },
  { id: "CT", description: "Chhattisgarh" },
  { id: "DN", description: "Dadra and Nagar Haveli and Daman and Diu" },
  { id: "DL", description: "Delhi" },
  { id: "GA", description: "Goa" },
  { id: "GJ", description: "Gujarat" },
  { id: "HR", description: "Haryana" },
  { id: "HP", description: "Himachal Pradesh" },
  { id: "JK", description: "Jammu and Kashmir" },
  { id: "JH", description: "Jharkhand" },
  { id: "KA", description: "Karnataka" },
  { id: "KL", description: "Kerala" },
  { id: "LA", description: "Ladakh" },
  { id: "LD", description: "Lakshadweep" },
  { id: "MP", description: "Madhya Pradesh" },
  { id: "MH", description: "Maharashtra" },
  { id: "MN", description: "Manipur" },
  { id: "ML", description: "Meghalaya" },
  { id: "MZ", description: "Mizoram" },
  { id: "NL", description: "Nagaland" },
  { id: "OD", description: "Odisha" },
  { id: "PY", description: "Puducherry" },
  { id: "PB", description: "Punjab" },
  { id: "RJ", description: "Rajasthan" },
  { id: "SK", description: "Sikkim" },
  { id: "TN", description: "Tamil Nadu" },
  { id: "TG", description: "Telangana" },
  { id: "TR", description: "Tripura" },
  { id: "UP", description: "Uttar Pradesh" },
  { id: "UT", description: "Uttarakhand" },
  { id: "WB", description: "West Bengal" },
];

export default indianStates;
